export const ADD_INGREDIENT='ADD_INGREDIENT';
export const REMOVE_INGREDIENT ='REMOVE_INGREDIENT';
export const INITIAL_INGREDIENT ='INITIAL_INGREDIENT';
export const ERROR_GETTING_INGREDIENT = 'ERROR_GETTING_INGREDIENT';
