export const ADD_INGREDIENT='ADD_INGREDIENT';
export const REMOVE_INGREDIENT ='REMOVE_INGREDIENT';
export const INITIAL_INGREDIENT ='INITIAL_INGREDIENT';
export const ERROR_GETTING_INGREDIENT = 'ERROR_GETTING_INGREDIENT';

export const ORDERING_BURGER_SUCCESS='ORDERING_BURGER_SUCCESS';
export const ORDERING_BURGER_FAILED='ORDERING_BURGER_FAILED';
export const ORDERING_BURGER_LOADING = 'ORDERING_BURGER_LOADING';
