export const ADD_INGREDIENT='ADD_INGREDIENT';
export const REMOVE_INGREDIENT ='REMOVE_INGREDIENT';
export const INITIAL_INGREDIENT ='INITIAL_INGREDIENT';
export const ERROR_GETTING_INGREDIENT = 'ERROR_GETTING_INGREDIENT';

export const ORDERING_BURGER_SUCCESS='ORDERING_BURGER_SUCCESS';
export const ORDERING_BURGER_FAILED='ORDERING_BURGER_FAILED';
export const ORDERING_BURGER_LOADING = 'ORDERING_BURGER_LOADING';

export const INITIAL_ORDERED = 'INITIAL_ORDERED';

export const FETCHING_ORDERS_LOADING = 'FETCHING_ORDERS_LOADING';
export const FETCHING_ORDERS_SUCCESS = 'FETCHING_ORDERS_SUCCESS';
export const FETCHING_ORDERS_FAILED = 'FETCHING_ORDERS_FAILED';

export const AUTH_LOADING = 'AUTH_START';
export const AUTH_SUCCESS ='AUTH_SUCCESS';
export const AUTH_FAILED='AUTH_FAILED';
